name: CI/CD workflow

on:
  push:
     branches:
         - main
  pull_request:
      branches:
        - main

jobs:
  pre-commit-scan:
     runs-on: ubuntu-latest

     steps:
         - name: setup java
           uses: actions/setup-java@v4
           with:
              distribution: 'temurin'
              java-version: '21'    

         - name: checkout code
           uses: actions/checkout@v4

         - name: Gitleaks scan
           uses: Zricethezav/gitleaks-action@v1.3.0
           with:
              args: --path=.
         - name: oss scan
           run: mvn ossindex:audit

         - name: owasp Scan
           if: false
           run: mvn org.owasp:dependency-check-maven:check

         - name: Build code and create docker images
           run: mvn clean install docker:build -Dimage.registry=${{secrets.DOCKER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME
           

           

           
          
           
       
        
